[package]
name = "quarkmq-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
crc32fast = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
