[package]
name = "quarkmq-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
kafka-protocol = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
